imagePullSecret: regcred
container:
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  livenessProbe: 
    enabled: false
  readinessProbe:
    enabled: false
  volumeMounts:
    - mountPath: /app/config/config.yaml
      subPath: config.yaml
      name: secret2ssl-config
      readOnly: false
volumes:
  - name: secret2ssl-config
    configMap:
      name: secret2ssl-config
serviceAccountName: secret2ssl
service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
